### ISSUE TITLE
Multiplex - one snowflake proxy should be able to support multiple clients

### ISSUE THREAD

**Issue by keroserene** [keroserene/snowflake#11]

**Comment by arlolra** [comment]
This is now https://trac.torproject.org/projects/tor/ticket/25601

**Comment by glamrock** [comment]
@arlolra Why the sudden migration to tor trac?

**Comment by arlolra** [comment]
That just seems to be where development is happening these days.

Since we've been including the snowflake client in alpha builds of Tor Browser, there're more bugs reported on trac, and I'd rather not have to look in two places when trying to determine what needs to be done.

While I have you here, how's the cupcake transition coming along? :)

**Comment by glamrock** [comment]
I was benched for a while, so still catching up on work-work, but it's in the queue. =)
