### ISSUE TITLE
[Question] What to work on during our hackathon tomorrow?

### ISSUE THREAD

**Issue by elimisteve** [keroserene/snowflake#36]
Hi Serene! I'm Steve Phillips. I don't think we got to meet during Aaron Swartz Day but I saw you during the Tor panel. Important work you all are doing!

Speaking of which, I don't know if Mike or Ms. Lovecraft happened to mention the privacy hackathon I'm putting on tomorrow at Noisebridge, but there is interest from several people in contributing to Snowflake! What should people focus on?

If you want to label or create issues for us to work on, or if there some among the existing 15 that you want help with, let me know by tomorrow afternoon and I'll show people what to do!

Or if you want to come by to help people in person, go right ahead.

2pm-10pm tomorrow at Noisebridge: https://www.meetup.com/Cypherpunks-Write-Code/events/235899233/

**Comment by keroserene** [comment]
Hi Steve! Thanks you for letting me know -- so glad to hear of the interest!

Alpha snowflake is being released in the linux Tor-Browser-Bundle release soon, and there is much to do. The most important / urgent categories of effort to focus on are:
- Increase distribution / capacity of the snowflake network. (This involves improving the robustness of the snowflake proxy and the functionality of the Broker, and externally: Cupcake's integration with snowflake, and work on the websocket relay.)
- Reproducible builds on OSX (https://github.com/keroserene/snowflake/issues/38) and Windows (https://github.com/keroserene/snowflake/issues/39) so that we can include Snowflake in those wider Tor Browser Bundle releases
- Improve metrics for detecting onset of censorship

So there is certainly lots of high-impact work that we need help with! Here's a fairly simple [technical overview](http://keroserene.net/snowflake/technical/) for people getting started.

In this codebase, here are some issues related to those tasks ranked roughly by importance / likelihood of completion within a limited time-frame:
- Proxy Options page (to let people set their opt-in status) https://github.com/keroserene/snowflake/issues/21 
- Disable proxy for TBB user agents https://github.com/keroserene/snowflake/issues/37 
- Improve metrics instrumentation on Broker https://github.com/keroserene/snowflake/issues/29 
- Headless Snowflake Proxy https://github.com/keroserene/snowflake/issues/30 
- Mac + Windows reproducible builds https://github.com/keroserene/snowflake/issues/38, https://github.com/keroserene/snowflake/issues/39
- Retrieve ICE server info from broker https://github.com/keroserene/snowflake/issues/3
- Test Snowflake in different NAT topologies https://github.com/keroserene/snowflake/issues/20 
- Setup TURN servers https://github.com/keroserene/snowflake/issues/18 (fairly independent of the code here. Just need to set up a TURN relay somewhere and try running a snowflake client through it)

Furthermore, there's plenty of minor TODOs sprinkled throughout the code which are more bite-sized which people are free to take on. General improvements to code quality + testing would be awesome. There's also room for improvement in the underlying [go-webrtc](https://github.com/keroserene/go-webrtc) library.

Of course, I'm sure there's plenty of other issues I've missed. So if people find additional bugs or issues to address that would be awesome.

There's also important work external to this codebase but crucial to our success. For instance, if someone can push this forward https://trac.torproject.org/projects/tor/ticket/18654 that would amazing.

Anyhow, would love to provide help and guidance from afar when I can (I won't be around in-person today, alas). I realize there's a lot of context involved to reasonably navigate this code, so if anything is unclear don't hesitate to reach out. Hope this is helpful.

Have an amazing hackathon!

**Comment by elimisteve** [comment]
Hey @keroserene, thanks for the excellent write-up! 

Quick update: our first hackathon went great -- about 25 people showed up, and I estimate 100 human hours of development and design work -- though we ended up not having Go programmers come by as some had planned. But I've linked to this very issue in the [Hackathon 1 summary](https://github.com/cpunkswritecode/hackathons#hackathon-1-20161217--noisebridge), and I will absolutely include Snowflake as an official focus in Hackathon 2 since you've so streamlined the developer onboarding process to this important project of yours.

Sorry for the delayed feedback, and I hope that more Go people show up during the next hackathon :-). Thanks!
